### ISSUE TITLE
Init: points d'attention

### ISSUE THREAD

**Issue by ogizanagi** [rix-fr/rix#2]
### Config

- [x] Fixer ou supprimer liens compte Instagram ?
- [x] Lien GG maps ? (mm que Elao actuellement)
- [x] Contact email ? Actuellement: contact@rix.com
- [x] Jobs email ? Actuellement: jobs@rix.com
- [x] Birthdate de la société ? (utilisé pour calculer nb années XP, année affiché dans le ©, …)
- [x] security.txt infos => voir l'email à mettre

### Contenus

- [x] titres et descriptions RSS
- [x] Contenus pages legal & confidentialité
- [x] Check toutes les metas title & descr de chaque pages, images pour les réseaux sociaux, etc…

### Front

- [x] Favicon & main logos (à améliorer)
- [x] Génération signatures mails ? => template à update

## Prod

- [x] A-t-on un Matomo dédié ? A quelle URL ? metrics.rix.com ?
- [x] Prod SSH config, urls & deploy keys

**Comment by gfaivre** [comment]
# Config
- Pas de lien instagram
- Pas de lien Gmap, eventuellement OpenStreetMap
- Contact email ? contact@rix.fr
- Jobs email ? jobs@rix.fr
- Birthdate de la société ? 31 Mars 2020
- security.txt infos => security@rix.fr
