### ISSUE TITLE
Quelques calages

### ISSUE THREAD

**Issue by gfaivre** [rix-fr/rix#22]
Sur `contents/main`

### Page mentions légales

- Les liens des coordonnées ne semblent pas être stylisés.
![Capture d’écran du 2022-08-02 11-13-54](https://user-images.githubusercontent.com/400505/182339825-4bf22f4a-e53e-4292-9936-2a0a0c09a7d6.png)

- Il y a un petit chevauchement ici, je ne sais pas si on peut y faire grand chose
![Capture d’écran du 2022-08-02 11-15-52](https://user-images.githubusercontent.com/400505/182340280-089bd5dd-e784-43d9-ada4-319559d897a1.png)

### Home

- J'ai cassé la partie Open Source :)
![Capture d’écran du 2022-08-02 11-25-55](https://user-images.githubusercontent.com/400505/182341280-f1528ed8-9845-42c7-b4cb-7a9d2c5de236.png)

**Comment by sludovicdelys** [comment]
Merci @gfaivre 🙏🏽
