### ISSUE TITLE
[Question inté] - Ajouter des technos (images) sur la Homepage 

### ISSUE THREAD

**Issue by gfaivre** [rix-fr/rix#24]
J'aimerais qu'on discute de ces icônes, est-ce qu'on en mets sur les autres fiches ?

![Capture d’écran du 2022-08-05 16-59-18](https://user-images.githubusercontent.com/400505/183104777-1d82a00e-df37-4a13-aae3-341b83cf8a47.png)

**Comment by sludovicdelys** [comment]
@gfaivre Sur la [maquette](https://www.figma.com/file/efooykznboxHpfPHUP29Mu/Rix?node-id=602%3A9165) on en a sur la page d'accueil, des services et dans le détail des études de cas.

**Comment by ameliedefrance** [comment]
@gfaivre j'suis pas sûre d'avoir compris ta question, tu parles de quelles pages ? 🙂

**Comment by gfaivre** [comment]
@ameliedefrance sur la home, avoir ici: 

![Capture d’écran du 2022-09-05 16-18-37](https://user-images.githubusercontent.com/400505/188470009-5bed488a-140b-44a4-a750-3091e7f444e2.png)

AWS / Google / OVH et Scaleway pour les deux premières sections (Conception sur mesure et Expertise Kubernetes).
Comme ça par ex (t'as tout a fait le droit de me dire que c'est :hankey: 

![Capture d’écran du 2022-09-05 16-24-48](https://user-images.githubusercontent.com/400505/188471076-1899b004-d09c-4a7a-92a0-9cc49b99aa1e.png)

**Comment by ameliedefrance** [comment]
@gfaivre Ma réponse est en deux parties 🤓

1. Tel que ça a été conçu, on ne pourra pas empiler 4 logos sur ces petits blocs service car on est limités par le bouton qui apparaît au hover. On a besoin d'une `height` en dur pour ce truc qui vient cacher les logos.
![Capture d’écran 2022-09-13 à 11 06 49](https://user-images.githubusercontent.com/25897625/189861296-9a8a49d5-e2d9-4e83-8ffb-8ece5546f884.png)

1.bis Mais c'est pas du tout de la 💩 ce que tu proposes ! Car on a une autre option.

2. On pourrait tout à afficher 3 logos sur la ligne et pas 2 (4 je pense que ça va être serré, la question c'est est-ce que les 4 technos sont importantes ?) Ça nécessite une micro modif d'inté mais vraiment c'est l'histoire de quelques minutes.
![Capture d’écran 2022-09-13 à 11 08 04](https://user-images.githubusercontent.com/25897625/189862269-d6a6625c-7ffe-4d7c-8a58-69a13ed6806f.png)

**Comment by gfaivre** [comment]
Alors c'est les différents fournisseurs avec lesquels on peut travailler donc ça a son importance. 
Par contre on peut effectivement avoir un compromis, le temps de réfléchir à la question aussi, dans ce cas je mettrai en avant OVH , Scaleway et GCP.
